---
jobs:

- name: deploy-logsearch-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: logsearch-config
      trigger: true
    - get: common-prod
    - get: cg-s3-logsearch-release
    - get: logsearch-stemcell
  - task: logsearch-manifest
    config:
      platform: linux
      image: docker:///18fgsa/concourse-task
      inputs:
      - name: logsearch-config
      - name: common-prod
      run:
        path: logsearch-config/generate.sh
        args: ["common-prod/secrets.yml", "logsearch-manifest/manifest.yml"]
      outputs:
      - name: logsearch-manifest
  - put: logsearch-production-deployment
    params:
      cert: common-prod/boshCA.crt
      manifest: logsearch-manifest/manifest.yml
      releases:
        - cg-s3-logsearch-release/*.tgz
      stemcells:
        - logsearch-stemcell/*.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy logsearch on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed logsearch on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

resources:
- name: common-prod
  type: cg-common
  source:
    bucket_name: {{logsearch-private-bucket-production}}
    access_key_id: {{logsearch-private-access-key-id-production}}
    secret_access_key: {{logsearch-private-secret-access-key-production}}
    secrets_file: logsearch.yml
    secrets_passphrase: {{logsearch-production-private-passphrase}}
    bosh_cert: bosh.pem

- name: cg-s3-logsearch-release
  type: s3
  source:
    access_key_id: {{cg-s3-bosh-releases-access-key-id}}
    bucket: {{cg-s3-bosh-releases-bucket}}
    private: true
    regexp: logsearch-(.*).tgz
    secret_access_key: {{cg-s3-bosh-releases-secret-access-key}}

- name: logsearch-config
  type: git
  source:
    uri: {{cg-deploy-logsearch-git-url}}
    branch: {{cg-deploy-logsearch-git-branch}}

- name: logsearch-stemcell
  type: bosh-io-stemcell
  source:
    name: {{logsearch-stemcell}}

- name: logsearch-production-deployment
  type: bosh-deployment
  source:
    target: {{logsearch-production-deployment-bosh-target}}
    username: {{logsearch-production-deployment-bosh-username}}
    password: {{logsearch-production-deployment-bosh-password}}
    deployment: {{logsearch-production-deployment-bosh-deployment}}
    ignore_ssl: false

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
